Create Icon Link Component in Footer
DaleStudy/leetcode-website pull request #77
Opened 2024-06-26 00:32 UTC by bhyun-kim

## Checklist before merging

- [ ] Link an issue with the pull request
- [ ] Ensure no errors or warnings on the browser console
- [ ] Avoid additional major pushes after approval (if necessary, request a new review)

2024-06-26 02:59 UTC, sounmind requested changes
병현님~ 컴포넌트 구현하시느라 고생하셨습니다.

제가 이전에 말씀드린 형태는 아래 예시처럼 다양한 종류의 이미지 엘리먼트들을 외부에서 전달하는 방식이었습니다.

```html
// png
<ds-footer-icon href="something">
  <img src="something.png" alt="something" />
</ds-footer-icon>

// jpeg
<ds-footer-icon href="something">
  <img src="something.jpeg" alt="something" />
</ds-footer-icon>

// svg
<ds-footer-icon href="something">
  <img src="something.svg" alt="something" />
</ds-footer-icon>
```

2024-06-26 02:59 UTC, sounmind commented on components/footer-icon.js
> +    `;
CSS 작성 형식에 오류가 있는 것 같아요.
slot 부분에서 닫힌 괄호가 없습니다.

```suggestion
    return css`
      .footer-icon {
        display: inline-block;
      }
      
      slot {
      	display: none;
    	}
  	`;
```

2024-06-26 02:59 UTC, sounmind commented on components/footer-icon.js
> +customElements.define("footer-icon", FooterIcon);
저희가 합의한 작성 패턴에 따라 웹 컴포넌트 이름을 작성해주세요.
```suggestion
customElements.define("ds-footer-icon", FooterIcon);
```

2024-06-26 14:56 UTC, bhyun-kim commented
> 병현님~ 컴포넌트 구현하시느라 고생하셨습니다.
> 
> 제가 이전에 말씀드린 형태는 아래 예시처럼 다양한 종류의 이미지 엘리먼트들을 외부에서 전달하는 방식이었습니다.
> 
> ```
> // png
> <ds-footer-icon href="something">
>   <img src="something.png" alt="something" />
> </ds-footer-icon>
> 
> // jpeg
> <ds-footer-icon href="something">
>   <img src="something.jpeg" alt="something" />
> </ds-footer-icon>
> 
> // svg
> <ds-footer-icon href="something">
>   <img src="something.svg" alt="something" />
> </ds-footer-icon>
> ```



> 병현님~ 컴포넌트 구현하시느라 고생하셨습니다.
> 
> 제가 이전에 말씀드린 형태는 아래 예시처럼 다양한 종류의 이미지 엘리먼트들을 외부에서 전달하는 방식이었습니다.
> 
> ```
> // png
> <ds-footer-icon href="something">
>   <img src="something.png" alt="something" />
> </ds-footer-icon>
> 
> // jpeg
> <ds-footer-icon href="something">
>   <img src="something.jpeg" alt="something" />
> </ds-footer-icon>
> 
> // svg
> <ds-footer-icon href="something">
>   <img src="something.svg" alt="something" />
> </ds-footer-icon>
> ```

https://github.com/DaleStudy/leetcode-website/assets/94029750/6dbc33bc-1704-4f6f-b0a5-6c29c7fdf5fb

지난번에 이야기하신대로 jpg 파일이랑 URL이 전달되고 렌더링이 잘 되는 상황입니다. 다만 작성된 코드의 형태는 아래와 같은데요. 지난번에 의견 주셨던게 slot을 이용해서 svg path (여기서 path는 vector를 표현하는 path를 말합니다.)를 입력하거나, 이미지 파일의 경로, 혹은 URL 경로를 입력하는 것으로 기억해서요. 지금 올려주신거랑 다른데 혹시 어떻게하는게 좋을까요? 

<footer-icon
   type="img"
   href="https://www.daleseo.com/"
>
  images\roadmap.png
</footer-icon>

2024-06-26 15:02 UTC, bhyun-kim commented on components/footer-icon.js
> +customElements.define("footer-icon", FooterIcon);
넵! 확인해서 수정했습니다. 감사합니다.

2024-06-26 15:02 UTC, bhyun-kim commented on components/footer-icon.js
> +    `;
넵! 확인해서 수정했습니다. 감사합니다.

2024-06-26 16:23 UTC, sounmind commented
최종 형태
```html
  <ds-footer-icon
    href="https://github.com/DaleSeo"
    width="24px"
    height="24px"
    iconSrc="images\human.png"
    iconAlt="human-icon"
  ></ds-footer-icon>
```

2024-06-26 16:55 UTC, bhyun-kim commented
> 최종 형태
> 
> ```
>   <ds-footer-icon
>     href="https://github.com/DaleSeo"
>     width="24px"
>     height="24px"
>     iconSrc="images\human.png"
>     iconAlt="human-icon"
>   ></ds-footer-icon>
> ```

오늘 디스커션하면서 결정해주셨던 최종형태와, validateAttributes, 그리고 icon 파일들을 추가하였습니다. 시간 내주셔서 감사드려요!

2024-06-26 16:59 UTC, sounmind commented on components/footer-icon.js
> +      <a href="${href}">
아이콘 클릭했을 때 새 창으로 열리도록 해주시겠어요?
```suggestion
      <a href="${href}" target="_blank">
```

2024-06-26 17:00 UTC, sounmind commented on components/footer-icon.js
> +        ></img>
```suggestion
        <img
          src="${iconSrc}"
          alt="${iconAlt}"
        />
```

2024-06-26 17:02 UTC, sounmind commented on components/footer-icon.js
> +    }
validExtensions이 바뀔 때마다 에러 메시지도 함께 바뀌도록 작성할 수는 있을까요?

2024-06-26 17:03 UTC, sounmind commented on components/footer-icon.js
> +    const extension = iconSrc.slice(-4).toLowerCase();
(변경요청아님) 지원해야 하는 이미지 확장자가 5글자 이상인 것이 생기면 다시 이것을 바꿔야 할까요?

2024-06-26 17:06 UTC, sounmind commented on components/footer-icon.js
> +      );
이렇게 변경해볼 수도 있겠네요.
```suggestion
		const validExtensions = [".svg", ".png", ".jpg", ".jpeg"];
		
		const maxExtensionLength = Math.max(...validExtensions.map(ext => ext.length));
		const extension = iconSrc.slice(-maxExtensionLength).toLowerCase();
		
		if (!validExtensions.includes(extension)) {
		  const validExtensionsString = validExtensions.join(', ');
		  throw new Error(
		    `The "iconSrc" attribute must end with one of the following extensions: ${validExtensionsString}.`
		  );
		}
```

2024-06-26 20:16 UTC, bhyun-kim commented on components/footer-icon.js
> +      <a href="${href}">
확인해서 변경했습니다.

2024-06-26 20:25 UTC, bhyun-kim commented on components/footer-icon.js
> +      );
아래 [03bf518](https://github.com/DaleStudy/leetcode-website/pull/77/commits/03bf518aac19b054fccc68ef1ebf505114598292) commit에서 해당 내용 반영했습니다! 피드백 감사드립니다.

2024-06-27 01:15 UTC, sounmind approved these changes

2024-06-27 01:18 UTC, sounmind commented
컴포넌트를 작성하면서 알게된 새로운 개념들을 꼭 나중에라도 조사해주세요!

2024-06-27 02:00 UTC, bhyun-kim commented
넵 알겠습니다! 확인+리뷰 감사합니다.

2024-06-27 03:46 UTC, merged